// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "libspu/mpc/cheetah/permute.h"

#include "libspu/mpc/cheetah/secret_shared_shuffle.h"
#include "libspu/mpc/cheetah/state.h"
#include "libspu/mpc/cheetah/type.h"
#include "libspu/mpc/common/prg_state.h"
#include "libspu/mpc/utils/permute.h"
#include "libspu/mpc/utils/ring_ops.h"

namespace spu::mpc::cheetah {

NdArrayRef RandPermM::proc(KernelEvalContext* ctx,
                           const Shape& shape) const {
  NdArrayRef out(makeType<PShrTy>(), shape);

  // genPriv() is party-local: the other party does not learn this seed.
  auto* prg_state = ctx->getState<PrgState>();
  const auto seed = prg_state->genPriv(FieldType::FM64, {1});

  NdArrayView<uint64_t> seed_view(seed);
  const auto perm = genRandomPerm(out.numel(), seed_view[0]);

  NdArrayView<uint64_t> out_view(out);
  pforeach(0, out.numel(), [&](int64_t idx) {
    out_view[idx] = static_cast<uint64_t>(perm[idx]);
  });

  return out;
}

NdArrayRef PermAM::proc(KernelEvalContext* ctx, const NdArrayRef& in,
                        const NdArrayRef& perm) const {
  SPU_ENFORCE(in.numel() == perm.numel(),
              "input/permutation size mismatch: {} vs {}",
              in.numel(), perm.numel());

  const int64_t n = in.numel();
  SPU_ENFORCE(n > 0, "perm_am expects a non-empty input");

  // PermuteAndShare requires a power-of-two vector length. Extend the
  // protocol domain internally and keep all padded positions fixed by
  // both parties' private permutations. The public API still returns
  // exactly the original n elements.
  int64_t protocol_n = 1;
  while (protocol_n < std::max<int64_t>(n, 2)) {
    protocol_n <<= 1;
  }

  auto* comm = ctx->getState<Communicator>();
  auto* ot_state = ctx->getState<CheetahOTState>();

  // Use the first Cheetah OT instance for this sequential shuffle.
  ot_state->LazyInit(comm);
  auto ot = ot_state->get();

  // PermuteAndShare currently accepts shared_ptr<Communicator>, while
  // KernelEvalContext owns the Communicator state. This non-owning alias
  // is valid for the duration of this synchronous kernel invocation.
  std::shared_ptr<Communicator> comm_ref(
      comm, [](Communicator*) {});

  const auto field = in.eltype().as<AShrTy>()->field();

  int bit_width = 0;
  std::vector<uint128_t> local_share(
      static_cast<size_t>(protocol_n), 0);

  DISPATCH_ALL_FIELDS(field, "cheetah_perm_am_load", [&]() {
    bit_width = static_cast<int>(sizeof(ring2k_t) * 8);

    NdArrayView<ring2k_t> in_view(in);
    for (int64_t i = 0; i < n; ++i) {
      local_share[static_cast<size_t>(i)] =
          static_cast<uint128_t>(in_view[i]);
    }
  });

  const uint128_t mask =
      bit_width == 128
          ? ~static_cast<uint128_t>(0)
          : (static_cast<uint128_t>(1) << bit_width) - 1;

  // Each rank owns one private permutation generated by RandPermM.
  // The convention is:
  //
  //   pi(x)[i] = x[permutation[i]].
  //
  PermVector local_perm = ring2pv(perm);

  SPU_ENFORCE(
      static_cast<int64_t>(local_perm.size()) == n);

  // Extend pi on [0,n) to pi' on [0,protocol_n) by fixing every
  // padding position. Therefore cropping the final shares back to n
  // exactly recovers the original permutation semantics.
  local_perm.resize(static_cast<size_t>(protocol_n));
  for (int64_t i = n; i < protocol_n; ++i) {
    local_perm[static_cast<size_t>(i)] = i;
  }

  // CipherGPT Secret-Shared Shuffle uses a public power-of-two
  // subpermutation size T. Keep T modest while allowing small inputs.
  const int64_t T = std::min<int64_t>(protocol_n, 8);

  const int64_t rank =
      static_cast<int64_t>(comm->getRank());

  // Apply P0's private permutation, then P1's private permutation.
  //
  // For each round:
  //   - permutation owner locally permutes its own additive share;
  //   - PermuteAndShare securely permutes the other party's share;
  //   - adding both pieces gives fresh shares of pi(x).
  for (int64_t owner = 0; owner < 2; ++owner) {
    const bool owns_permutation = rank == owner;

    std::vector<uint128_t> remote_part;

    if (owns_permutation) {
      remote_part =
          secret_shared_shuffle::PermuteAndShare(
              comm_ref,
              ot,
              owner,
              protocol_n,
              T,
              absl::MakeConstSpan(local_perm),
              absl::Span<const uint128_t>(),
              bit_width);
    } else {
      remote_part =
          secret_shared_shuffle::PermuteAndShare(
              comm_ref,
              ot,
              owner,
              protocol_n,
              T,
              absl::Span<const int64_t>(),
              absl::MakeConstSpan(local_share),
              bit_width);
    }

    SPU_ENFORCE(
        static_cast<int64_t>(remote_part.size()) == protocol_n);

    if (owns_permutation) {
      std::vector<uint128_t> next_share(
          static_cast<size_t>(protocol_n));

      for (int64_t i = 0; i < protocol_n; ++i) {
        const int64_t src =
            local_perm[static_cast<size_t>(i)];

        SPU_ENFORCE(src >= 0 && src < protocol_n);

        next_share[static_cast<size_t>(i)] =
            (remote_part[static_cast<size_t>(i)] +
             local_share[static_cast<size_t>(src)]) &
            mask;
      }

      local_share = std::move(next_share);
    } else {
      local_share = std::move(remote_part);
    }
  }

  NdArrayRef out(in.eltype(), in.shape());

  DISPATCH_ALL_FIELDS(field, "cheetah_perm_am_store", [&]() {
    NdArrayView<ring2k_t> out_view(out);
    for (int64_t i = 0; i < n; ++i) {
      out_view[i] =
          static_cast<ring2k_t>(
              local_share[static_cast<size_t>(i)]);
    }
  });

  return out;
}

}  // namespace spu::mpc::cheetah
