load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "secure_router_reference",
    srcs = [
        "secure_router_reference.py",
        "switch_moe_reference.py",
    ],
    main = "secure_router_reference.py",
    deps = [
        "//spu:api",
        "//spu/utils:simulation",
    ],
)

py_binary(
    name = "secure_moe_correctness",
    srcs = [
        "secure_moe_correctness.py",
        "switch_moe_reference.py",
    ],
    main = "secure_moe_correctness.py",
    deps = [
        "//spu:api",
        "//spu/intrinsic:all_intrinsics",
        "//spu/utils:simulation",
    ],
)
